In [38]:
from cogent3 import get_code, DNA
import numpy as np

In [18]:
code = get_code()

In [118]:
code = get_code()
num_substitutions = np.zeros(3)
num_substitutions_by_from = np.zeros((4, 3))
num_strand_symmetric = np.zeros(3)
num_strand_symmetric_by_from = np.zeros((4, 3))
num_synonymous = np.zeros(3)
num_synonymous_by_from = np.zeros((4, 3))
num_synonymous_transitions = np.zeros(3)
nuc_key = {c: i for i, c in enumerate('ACGT')}
for codon in code.codons.keys():
    if code[codon] == '*':
        continue
    for pos in range(3):
        fr = codon[pos]
        count = 0
        for to in set('ACGT') - {fr}:
            to_codon = ''.join(c if i != pos else to for i, c in enumerate(codon))
            if code[to_codon] == '*':
                continue
            num_substitutions[pos] += 1
            num_substitutions_by_from[nuc_key[fr], pos] += 1
            forward_synonymous = code[codon] == code[to_codon]
            num_synonymous[pos] += forward_synonymous
            num_synonymous_by_from[nuc_key[fr], pos] += forward_synonymous
            num_synonymous_transitions[pos] += forward_synonymous and {fr, to} in ({'A', 'G'}, {'C', 'T'})
            reverse_synonymous = code[DNA.complement(codon)] == code[DNA.complement(to_codon)]
            num_strand_symmetric[pos] += \
                '*' not in {code[DNA.complement(codon)], code[DNA.complement(to_codon)]} and \
                forward_synonymous == reverse_synonymous
            num_strand_symmetric_by_from[nuc_key[fr], pos] += \
                '*' not in {code[DNA.complement(codon)], code[DNA.complement(to_codon)]} and \
                forward_synonymous == reverse_synonymous

In [119]:
num_substitutions

array([174., 176., 176.])

In [120]:
num_strand_symmetric

array([140., 160., 100.])

In [121]:
num_synonymous

array([  8.,   0., 126.])

In [122]:
num_synonymous_transitions

array([ 4.,  0., 58.])

In [123]:
num_strand_symmetric / num_substitutions * 100

array([80.45977011, 90.90909091, 56.81818182])

In [124]:
num_synonymous / num_substitutions * 100

array([ 4.59770115,  0.        , 71.59090909])

In [125]:
num_synonymous_transitions / num_synonymous * 100

array([50.        ,         nan, 46.03174603])

In [126]:
num_substitutions_by_from

array([[45., 42., 42.],
       [45., 45., 45.],
       [45., 44., 44.],
       [39., 45., 45.]])

In [129]:
num_synonymous_by_from

array([[ 2.,  0., 31.],
       [ 4.,  0., 33.],
       [ 0.,  0., 29.],
       [ 2.,  0., 33.]])

In [127]:
num_strand_symmetric_by_from

array([[32., 39., 25.],
       [38., 41., 25.],
       [38., 41., 25.],
       [32., 39., 25.]])

In [128]:
num_strand_symmetric_by_from / num_substitutions_by_from * 100

array([[71.11111111, 92.85714286, 59.52380952],
       [84.44444444, 91.11111111, 55.55555556],
       [84.44444444, 93.18181818, 56.81818182],
       [82.05128205, 86.66666667, 55.55555556]])

In [131]:
num_synonymous_by_from / num_substitutions_by_from * 100

array([[ 4.44444444,  0.        , 73.80952381],
       [ 8.88888889,  0.        , 73.33333333],
       [ 0.        ,  0.        , 65.90909091],
       [ 5.12820513,  0.        , 73.33333333]])

In [132]:
num_synonymous_by_from.sum(axis=1) / num_substitutions_by_from.sum(axis=1) * 100

array([25.58139535, 27.40740741, 21.80451128, 27.13178295])